### ISSUE TITLE
Add a polyfill for phpunit 4 to 6

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-tools#29]
https://github.com/GoogleCloudPlatform/php-docs-samples/pull/530/commits/f43e5e304d38bc58f83d64ea02771dcd32548360

**Comment by chingor13** [comment]
Can you add motivation for why this is necessary for posterity sake?

**Comment by tmatsuo** [comment]
PHPUnit 4 became EOL long time ago. However, there are some testing tools that depends on PHPUnit4. An example of this is [Silex WebTestCase](https://silex.symfony.com/api/master/Silex/WebTestCase.html). This shim allows you to upgrade to PHPUnit 6 very easily, just by installing the shim in your bootstrap file.
