### ISSUE TITLE
Symfony Console version

### ISSUE THREAD

**Issue by bkilshaw** [GoogleCloudPlatform/php-tools#51]
Requires Symfony Console 2 or 3 and doesn't support version 4.

**Comment by davidpv** [comment]
I've got same problem here with Symfony 4

**Comment by PeppeC** [comment]
Same here, it's unusable with Laravel 5.7

**Comment by bshaffer** [comment]
We can for sure make this fix, but, is there a reason you're including this repository in your Symfony/Laravel apps? This package should always be required as a dev package and so never conflict unless you're consuming it directly. If you're consuming it directly, that's awesome! I'd love to know what you're using it for.

**Comment by PeppeC** [comment]
Thanks for your quick reply. My idea is to use it to run migrations on post-install-cmd composer script, as last stage of a CI flow on App Engine using Cloud Sql. I haven't found other solutions for that, do you think this is a viable solution?

**Comment by bshaffer** [comment]
I mean, why do you need `google/cloud-tools`? What you just described is what the symfony console component does.

**Comment by knao124** [comment]
@bshaffer I will be very happy to use new release tag `v0.8.6` which includes #52
